config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homepage/index'

  root 'homepage#index'

  resources :requisitos
  resources :regra_negocios
  resources :diagramas
  resources :glossarios
  resources :projetos
  resources :users

end

app/models/requisito.rb
class Requisito < ActiveRecord::Base
end

app/controllers/requisitos_controller.rb
class RequisitosController < ApplicationController
  before_action :set_requisito, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /requisitos
  # GET /requisitos.json
  def index
    @requisitos = Requisito.all
  end

  # GET /requisitos/1
  # GET /requisitos/1.json
  def show
  end

  # GET /requisitos/new
  def new
    @requisito = Requisito.new
  end

  # GET /requisitos/1/edit
  def edit
  end

  # POST /requisitos
  # POST /requisitos.json
  def create
    @requisito = Requisito.new(requisito_params)

    respond_to do |format|
      if @requisito.save
        format.html { redirect_to @requisito, notice: 'Requisito was successfully created.' }
        format.json { render :show, status: :created, location: @requisito }
      else
        format.html { render :new }
        format.json { render json: @requisito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requisitos/1
  # PATCH/PUT /requisitos/1.json
  def update
    respond_to do |format|
      if @requisito.update(requisito_params)
        format.html { redirect_to @requisito, notice: 'Requisito was successfully updated.' }
        format.json { render :show, status: :ok, location: @requisito }
      else
        format.html { render :edit }
        format.json { render json: @requisito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requisitos/1
  # DELETE /requisitos/1.json
  def destroy
    @requisito.destroy
    respond_to do |format|
      format.html { redirect_to requisitos_url, notice: 'Requisito was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requisito
      @requisito = Requisito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def requisito_params
      params.require(:requisito).permit(:siglaRequisito, :nomeRequisito, :descricaoRequisito, :tipoRequisito, :prioridade)
    end
end

app/helpers/requisitos_helper.rb
module RequisitosHelper
end

app/views/requisitos/_form.html.erb
<%= form_for(@requisito) do |f| %>
  <% if @requisito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@requisito.errors.count, "error") %> prohibited this requisito from being saved:</h2>

      <ul>
      <% @requisito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :siglaRequisito, "Sigla" %><br>
    <%= f.text_field :siglaRequisito %>
  </div>
  <div class="field">
    <%= f.label :nomeRequisito, "Nome" %><br>
    <%= f.text_field :nomeRequisito %>
  </div>
  <div class="field">
    <%= f.label :descricaoRequisito, "Descricao" %><br>
    <%= f.text_field :descricaoRequisito %>
  </div>
  <div class="field">
    <%= f.label :tipoRequisito, "Tipo" %><br>
    <%= f.text_field :tipoRequisito %>
  </div>
  <div class="field">
    <%= f.label :prioridade, "Prioridade" %><br>
    <%= f.text_field :prioridade %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar"%>
  </div>
<% end %>

app/views/requisitos/edit.html.erb
<h1>Editar Requisito</h1>

<%= render 'form' %>

<%= link_to 'Ir para Requisitos', requisitos_path %>

app/views/requisitos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requisitos</h1>

<table>
  <thead>
    <tr>
      <th>Sigla</th>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Tipo</th>
      <th>Prioridade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requisitos.each do |requisito| %>
      <tr>
        <td><%= requisito.siglaRequisito %></td>
        <td><%= requisito.nomeRequisito %></td>
        <td><%= requisito.descricaoRequisito %></td>
        <td><%= requisito.tipoRequisito %></td>
        <td><%= requisito.prioridade %></td>
        <td><%= link_to 'Exibir', requisito %></td>
        <td><%= link_to 'Editar', edit_requisito_path(requisito) %></td>
        <td><%= link_to 'Excluir', requisito, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar Requisito', new_requisito_path %>

app/views/requisitos/new.html.erb
<h1>Novo Requisito</h1>

<%= render 'form' %>

<%= link_to 'Ir para Requisitos', requisitos_path %>

app/views/requisitos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sigla</strong>
  <%= @requisito.siglaRequisito %>
</p>

<p>
  <strong>Nome</strong>
  <%= @requisito.nomeRequisito %>
</p>

<p>
  <strong>Descricao</strong>
  <%= @requisito.descricaoRequisito %>
</p>

<p>
  <strong>Tipo</strong>
  <%= @requisito.tipoRequisito %>
</p>

<p>
  <strong>Prioridade</strong>
  <%= @requisito.prioridade %>
</p>

<%= link_to 'Ir para Requisitos', requisitos_path %>
<%= link_to 'Cadastrar Novo Requisto', new_requisito_path %>
<%= link_to 'Ir para Regras de Negocio', regra_negocios_path %>