config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homepage/index'

  root 'homepage#index'

  resources :requisitos
  resources :regra_negocios
  resources :diagramas
  resources :glossarios
  resources :projetos
  resources :users

end

app/models/projeto.rb
class Projeto < ActiveRecord::Base

end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController

  before_action :set_projeto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = Projeto.all
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
  end

  # GET /projetos/new
  def new
    @projeto = Projeto.new
  end

  # GET /projetos/1/edit
  def edit
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.new(projeto_params)

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Projeto criado com sucesso!' }
        format.json { render :show, status: :created, location: @projeto }
      else
        format.html { render :new }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    respond_to do |format|
      if @projeto.update(projeto_params)
        format.html { redirect_to @projeto, notice: 'Projeto atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @projeto }
      else
        format.html { render :edit }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url, notice: 'O seu projeto foi excluido!.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
      params.require(:projeto).permit(:nomeProjeto, :resumo)
    end
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/projetos/_form.html.erb
<%= form_for(@projeto) do |f| %>
  <% if @projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% @projeto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nomeProjeto, "Nome do Projeto" %><br>
    <%= f.text_field :nomeProjeto %>
  </div>
  <div class="field">
    <%= f.label :resumo, "Mini Mundo" %><br>
    <%= f.text_field :resumo %>
  </div>
  <div class="actions">
    <%= f.submit "Criar Projeto" %>
  </div>
<% end %>

app/views/projetos/edit.html.erb
<h1>Editar Projeto</h1>

<%= render 'form' %>

<%= link_to 'Listagem de Projetos', @projeto %> |
<%= link_to 'Voltar', projetos_path %>

app/views/projetos/index.html.erb
<p id="notice"><%= notice %></p>

  <ul>
    <li><%= current_user.email %></li>
  </ul>

  <ul>  
    <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
  </ul>

<h1>Listagem de Projetos</h1>

<table>
  <thead>
    <tr>
      <th>Nome do Projeto</th>
      <th>Mini Mundo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projetos.each do |projeto| %>
      <tr>
        <td><%= projeto.nomeProjeto %></td>
        <td><%= projeto.resumo %></td>
        <td><%= link_to 'Exibir', projeto %></td>
        <td><%= link_to 'Editar', edit_projeto_path(projeto) %></td>
        <td><%= link_to 'Excluir', projeto, method: :delete, data: { confirm: 'Voce tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Projeto', new_projeto_path %>

app/views/projetos/new.html.erb
<h1>Novo Projeto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', projetos_path %>

app/views/projetos/show.html.erb
<p>
  <strong>Nome do Projeto:</strong>
  <%= @projeto.nomeProjeto %>
</p>

<p>
  <strong>Mini Mundo:</strong>
  <%= @projeto.resumo %>
</p>

<%= link_to 'Voltar para projetos', projetos_path %>

<%= link_to 'Ir para Diagrama', diagramas_path %>