config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homepage/index'

  root 'homepage#index'

  resources :requisitos
  resources :regra_negocios
  resources :diagramas
  resources :glossarios
  resources :projetos
  resources :users

end

app/models/glossario.rb
class Glossario < ActiveRecord::Base
end

app/controllers/glossarios_controller.rb
class GlossariosController < ApplicationController
  before_action :set_glossario, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /glossarios
  # GET /glossarios.json
  def index
    @glossarios = Glossario.all
  end

  # GET /glossarios/1
  # GET /glossarios/1.json
  def show
  end

  # GET /glossarios/new
  def new
    @glossario = Glossario.new
  end

  # GET /glossarios/1/edit
  def edit
  end

  # POST /glossarios
  # POST /glossarios.json
  def create
    @glossario = Glossario.new(glossario_params)

    respond_to do |format|
      if @glossario.save
        format.html { redirect_to @glossario, notice: 'Glossario was successfully created.' }
        format.json { render :show, status: :created, location: @glossario }
      else
        format.html { render :new }
        format.json { render json: @glossario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /glossarios/1
  # PATCH/PUT /glossarios/1.json
  def update
    respond_to do |format|
      if @glossario.update(glossario_params)
        format.html { redirect_to @glossario, notice: 'Glossario was successfully updated.' }
        format.json { render :show, status: :ok, location: @glossario }
      else
        format.html { render :edit }
        format.json { render json: @glossario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /glossarios/1
  # DELETE /glossarios/1.json
  def destroy
    @glossario.destroy
    respond_to do |format|
      format.html { redirect_to glossarios_url, notice: 'Glossario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_glossario
      @glossario = Glossario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def glossario_params
      params.require(:glossario).permit(:siglaGlossario, :descricaoGlossario)
    end
end

app/helpers/glossarios_helper.rb
module GlossariosHelper
end

app/views/glossarios/_form.html.erb
<%= form_for(@glossario) do |f| %>
  <% if @glossario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@glossario.errors.count, "error") %> prohibited this glossario from being saved:</h2>

      <ul>
      <% @glossario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :siglaGlossario, "Sigla" %><br>
    <%= f.text_field :siglaGlossario %>
  </div>
  <div class="field">
    <%= f.label :descricaoGlossario, "Descricao" %><br>
    <%= f.text_field :descricaoGlossario %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/glossarios/edit.html.erb
<h1>Editar Glossario</h1>

<%= render 'form' %>

<%= link_to 'Ir para Glossarios', glossarios_path %>

app/views/glossarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>listagem de Glossarios</h1>

<table>
  <thead>
    <tr>
      <th>Sigla</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @glossarios.each do |glossario| %>
      <tr>
        <td><%= glossario.siglaGlossario %></td>
        <td><%= glossario.descricaoGlossario %></td>
        <td><%= link_to 'Exibir', glossario %></td>
        <td><%= link_to 'Editar', edit_glossario_path(glossario) %></td>
        <td><%= link_to 'Excluir', glossario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Glossario', new_glossario_path %>

app/views/glossarios/new.html.erb
<h1>Novo Glossario</h1>

<%= render 'form' %>

<%= link_to 'Ir para Glossarios', glossarios_path %>

app/views/glossarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sigla:</strong>
  <%= @glossario.siglaGlossario %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @glossario.descricaoGlossario %>
</p>

<%= link_to 'Finalizar', projetos_path %>